print(r'        |  /| |')
print(r'        |\/ \/|')
print(r'        |     |')
print(r'        |  S  |')
print(r'       /|     |')
print(r'  ____/ |    /|')
print(r' @|     |___/ |')
print("//_----'@|-.__|")
print("|| ''---||--\\'|")
print("||      ||   ||")
print("/|      ||   ||")
print("        /|     ")